version: "3.9"
services: 
  api-server:
    build: 
      context: .
      target: development
    volumes: 
      - type: bind
        source: ./api_server_mock
        target: /opt/api_server_mock/api_server_mock
    ports: 
      - "8080:8080"
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: mock_api_db
    ports:
      - "15432:5432"
    volumes: 
      - ./docker-scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql