version: "3.9"
services: 
  api-server:
    build: 
      context: .
      target: development
    volumes: 
      - type: bind
        source: ./api_server_mock
        target: /opt/api_server_mock/api_server_mock
    ports: 
      - "8080:8080"