mock_api_server:
  db:
    DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/mock_api_db"
    user: "postgres"
    password: "postgres"
    port: 5432
    host: db
    database: "mock_api_db"
    min_connection_count: 3
    max_connection_count: 10
fastapi_kwargs:
  debug: false
  docs_url: "/docs"
  openapi_prefix: ""
  openapi_url: "/openapi.json"
  redoc_url: "/redoc"
  title: "FastAPI example application"
  version: "0.0.0"
api_prefix: "/api/v1"
allowed_hosts: "*"