"""initial migration

Revision ID: 92e700fd35cc
Revises: 
Create Date: 2022-11-05 19:28:49.339324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92e700fd35cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('resource',
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('resource_data',
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_resource_data_project_id_project')),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name=op.f('fk_resource_data_resource_id_resource')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_data')),
    sa.UniqueConstraint('resource_id', 'project_id', name='project_resource_data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_data')
    op.drop_table('users')
    op.drop_table('resource')
    op.drop_table('project')
    # ### end Alembic commands ###
