"""add dates to the tables

Revision ID: e04ef5d27c69
Revises: 92e700fd35cc
Create Date: 2022-11-19 23:47:24.748432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04ef5d27c69'
down_revision = '92e700fd35cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('resource', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('resource', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('resource_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('resource_data', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('resource_data', 'updated_at')
    op.drop_column('resource_data', 'created_at')
    op.drop_column('resource', 'updated_at')
    op.drop_column('resource', 'created_at')
    op.drop_column('project', 'updated_at')
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
